default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  database: products_development
  template: template0

test:
  adapter: postgresql
  database: products_test
  template: template0
